**ARRAY MODIFICATION**

In [1]:
import numpy as np


In [7]:
#INSERT / ADD 

# SYNTAX => np.insert(array, index_no, value, axis= None)
'''
axis = 0 => row wise 
axis = 1 => col wise 
'''

arr = np.array([10,20,30,40,50,60])
print(arr)

new_arr = np.insert(arr, 2, 100, axis = 0) # axis = 0 is default
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [13]:
#insert in 2D

arr = np.array([[1,2],[3,4]])
print("Original : \n", arr)


row_arr = np.insert(arr, 1, [5,6], axis = 0 )
print("Inserting row wise : \n", row_arr)

col_arr = np.insert(arr, 1, [5,6], axis = 1 )
print("Inserting row wise : \n", col_arr)

flat_arr = np.insert(arr, 1, [5,6], axis = None ) # if axis = None then the element will add in flatten array
print("Inserting row wise : ", flat_arr)


Original : 
 [[1 2]
 [3 4]]
Inserting row wise : 
 [[1 2]
 [5 6]
 [3 4]]
Inserting row wise : 
 [[1 5 2]
 [3 6 4]]
Inserting row wise :  [1 5 6 2 3 4]


In [16]:
# append => add element at last

arr = np.array([1,2,3,4])
# new_arr = np.append(arr, 5)
new_arr = np.append(arr, [5,6])
new_arr


array([1, 2, 3, 4, 5, 6])

In [ ]:
# array concatination

arr1 = np.array([1,2])
arr2 = np.array([3,4])

new_Arr = np.concatenate((arr1, arr2), axis = 0) # in 1d no need of axis
new_Arr



array([ 2,  4,  8, 10])

In [38]:
arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[1,2],[5,6]])

new_arr = np.concatenate((arr1_2d, arr2_2d), axis = 1)
new_arr


array([[1, 2, 1, 2],
       [3, 4, 5, 6]])

In [43]:
# np.delete(array, index, axis = None)

arr = np.arange(10)
print(arr)

new_arr = np.delete(arr, 3, axis = None)
new_arr


# 2d array delete

arr_2d = np.array([[1,2],[3,4],[5,6]])
new_2d_arr = np.delete(arr_2d, 0, axis = 0)
new_2d_arr



[0 1 2 3 4 5 6 7 8 9]


array([[3, 4],
       [5, 6]])

In [46]:
# vstack => vertical stacking
# hstack => horizontal stacking

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[6,7],[3,4],[4,3]])

v_arr = np.vstack((arr1,arr2))
print(v_arr)
h_arr = np.hstack((arr1,arr2))
print(h_arr)


[[1 2]
 [3 4]
 [5 6]
 [6 7]
 [3 4]
 [4 3]]
[[1 2 6 7]
 [3 4 3 4]
 [5 6 4 3]]


In [ ]:
#SPLITTING

# np.split() => equal splitting 
# np.hsplit()
# np.vsplit()

arr = np.array([10,20,30,40,50,60])
np.split(arr, 3) # 2 here is the number of parts to divide the array

# split size should match 

[array([10, 20]), array([30, 40]), array([50, 60])]

In [103]:
# BROADCASTING

# without broadcasting
price = [100, 200, 300]
discount = 10 # 10% discount

final_price = [x-(x*discount/100) for x in price ]    #looping is slow
print(final_price)

#with broadcasting
arr = np.array([100,200,300])
final = arr - (arr * discount / 100)
print(final)


# to print in integer
print(final.astype(int))

[90.0, 180.0, 270.0]
[ 90. 180. 270.]
[ 90 180 270]


In [ ]:
# How numpy handle array of different shapes 

# 1d to 2d multiply

matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])

result = matrix + vector
print(result) 



array([[11, 22, 33],
       [14, 25, 36]])

In [106]:
# incompatible shapes [ERROR]

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2])

res = arr1 + arr2

# since the size is not matching or it cannot be expanded to match SO ERROR
print(res)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
#fixing using reshape


arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2])

#reshaping from (2,3) to (3,2)
arr1 = arr1.reshape((3,2))

#now it could perform broadcasting
res = arr1 + arr2

print(res)

[[2 4]
 [4 6]
 [6 8]]


In [ ]:
# HANDLING MISSING VALUES

# nan => not a number
# np.isnan(array) -> provides a boolean list with nan values as True 

In [110]:
arr = np.array([1,2,np.nan,4,5,np.nan,7])
print(np.isnan(arr))

[False False  True False False  True False]


In [113]:
# nan_to_num(array, nan=value)    default -> 0

# Replacing missing values

cleaned_arr = np.nan_to_num(arr)
print(cleaned_arr)

cleaned_arr = np.nan_to_num(arr, nan = 100)
print(cleaned_arr)


[1. 2. 0. 4. 5. 0. 7.]
[  1.   2. 100.   4.   5. 100.   7.]


In [115]:
# np.isinf(array) => checks if any infinite value like these: 10^10000, 1/0 present

arr = np.array([1,2,np.inf,6, -np.inf])

print(np.isinf(arr))

[False False  True False  True]


In [116]:
# replacing to finite value 

cleaned_arr = np.nan_to_num(arr, posinf = 1000, neginf = -1000)
#posinf to set positive infinite value and neginf for negative

cleaned_arr

array([    1.,     2.,  1000.,     6., -1000.])